const router = require('express').Router()
const dashboardControllers = require('../../controllers/dashboard')
const profileControllers = require('../../controllers/user')
const upload = require('../../middleware/userImageUpload')
const isAdmin = require('../../middleware/adminMW')
const isAuth  = require('../../middleware/auth')

router.get('/dashboard',isAdmin,dashboardControllers.getDashboard)
router.get('/dashboard/reports',isAdmin,dashboardControllers.getReports)
router.get('/dashboard/products',isAdmin,dashboardControllers.getProducts)
router.get('/dashboard/products/ajax',isAdmin,dashboardControllers.getProductsAJAX)
router.get('/dashboard/product/:product_id/bids',isAdmin,dashboardControllers.getBids)
router.get('/dashboard/orders',isAuth,dashboardControllers.myOrderPage)
router.get('/dashboard/orders/ajax',isAuth,dashboardControllers.myOrderPageAjax)
router.get('/dashboard/order/:order_id',isAuth,dashboardControllers.productDetailsBeforeCheckout)
router.get('/dashboard/order/:order_id/details',isAuth,dashboardControllers.orderDetails)
router.get('/dashboard/order/:order_id/manage',isAdmin,dashboardControllers.manageOrderPage)
router.get('/dashboard/product/:product_id',isAdmin,dashboardControllers.productDetails)
router.get('/dashboard/users',isAdmin,dashboardControllers.manageUsers)
router.get('/dashboard/users/ajax',isAdmin,dashboardControllers.getUsersAjax)
router.get('/dashboard/user/:user_id',isAdmin,dashboardControllers.getUserDetails)
router.post('/dashboard/user/:user_id/privileges',isAdmin,dashboardControllers.privileges)
router.post('/dashboard/user/:user_id/blacklist',isAdmin,dashboardControllers.blacklist)
router.post('/dashboard/product/:product_id/createOrder',isAdmin,dashboardControllers.makeProductSold)
router.post('/dashboard/create-product',isAdmin,dashboardControllers.createProduct)
router.post('/dashboard/delete-product',isAdmin,dashboardControllers.deleteProduct)
router.post('/dashboard/update-product',isAdmin,dashboardControllers.updateProduct)


//// MANAGE USERS 
router.get('/dashboard/profile',profileControllers.getProfile)
router.post('/dashboard/profile/image',upload.userUpload.single('upload_img'),profileControllers.uploadProfileImg)
router.post('/dashboard/profile/update',profileControllers.updateProfile)
module.exports = router 